version: 2.1

jobs:
  build_and_push_gem:
    working_directory: ~/choices
    resource_class: small
    docker:
      - image: amagidevops/mini_playlist:test_build_essential_v1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/choices

      - run:
          name: Set Credentials
          command: |
            mkdir -p $HOME/.gem
            touch $HOME/.gem/credentials
            chmod 0600 $HOME/.gem/credentials
            printf -- "---\n:github: Bearer ${GITHUB_TOKEN}\n" > $HOME/.gem/credentials

      # Build gem
      - run:
          name: Build gem
          command: |
            echo "export GEM_FILE=$(gem build | sed -n "s/^.*File: \(.*\.gem\)$/\1/p")" >> $BASH_ENV

      # Push gem to ruby gems github repository
      - run:
          name: Push gem to github rubygems repository
          command: gem push --key github ${GEM_FILE}

workflows:
  version: 2.1
  build_gem:
    jobs:
      - build_and_push_gem:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /vg-build-gem/
